** CLAUSULAS AVANZADAS DE SELECCION **
    SELECT AVG(PUNTOS) FROM 'JUGADORES' GROUP BY VALORACION; --AGRUPA DATOS IGUALES EN ESTE CASO DE VALORACION (5, 5, 5) | (7, 7, 7) (*AVG *COUNT *MAX *MIN *SUM)
    