**INSERTAR DATOS**

    INSERT INTO NOMBRE_TABLA (DNI, NOMBRE, APELLIDO) VALUES ('99999999X', 'FER', 'LOPEZ', NULL); --(NULL EN CASO DE QUE HAYA UNA CUARTA COLUMNA SIN RELLENAR)--
    INSERT INTO NOMBRE_TABLA (DNI, NOMBRE, APELLIDO) VALUES ('99999999X', 'FER', 'LOPEZ', DEFAULT); --(DEFAULT RELLENA EL CAMPO CON EL DATO ESTANDAR INTRODUCIDO)--
    INSERT INTO NOMBRE_TABLA (DNI, NOMBRE, APELLIDO) VALUES ('99999999X', 'FER', 'LOPEZ', DEFAULT), ('11111111S', 'JAIME', 'DOMINGUEZ', DEFAULT); --AÑADIR MAS COLUMNAS--
    INSERT INTO NOMBRE_TABLA (SET DNI = '99999999X', NOMBRE = 'FER', APELLIDO = 'LOPEZ') --ALTERNATIVA DE INSERCCIÓN--

    INSERT INTO CANTIDAD_VECES (IP, CANTIDAD, FECHA_ULTIMA) VALUES ('192.365.3.80', 1, NOW()) ON DUPLICATE KEY UPDATE CANTIDAD = CANTIDAD + 1, FECHA_ULTIMA = NOW();