**UPDATE DATOS (MODIFICAR DATOS)**

    UPDATE ALUMNOS /*NOMBRE_TABLA*/ SET TELEFONO /*NOMBRE_COLUMNA*/ = 653698632 WHERE DNI = '21365478X' /*CONDICIÓN SI NO SE LE CAMBIA A TODOS*/
    UPDATE ALUMNOS /*NOMBRE_TABLA*/ SET TELEFONO /*NOMBRE_COLUMNA*/ = 653698632 WHERE DNI = SELECT DNI FROM ALUMNOS2 WHERE NOMBRE = 'HUGO' /*CONDICIÓN QUE BUSCA EN OTRA TABLA*/

    UPDATE TABLA1, TABLA2, TABLA3 SET TABLA1.AVAL1 = TABLA2.BVAL2 WHERE TABLA1.ID = TABLA3.ID AND TABLA2.BVAL2 = TABLA3.CVAL1;

**BORRAR DATOS**

    DELETE FROM ALUMNOS WHERE DNI = '21365478X' /*CONDICIÓN SI NO SE LE BORRA A TODOS*/
    DELETE FROM ALUMNOS /*BORRA LAS FILAS Y DEJA LA TABLA VACIA*/
    TRUNCATE TABLE ALUMNOS /*BORRA LAS FILAS Y DEJA LA TABLA VACIA IGUAL QUE LA DE ARRIBA PERO ES MAS EFICIENTE YA QUE BORRA TODAS A LA VEZ EN VEZ DE UNA EN UNA*/