CREATE DATABASE IF NOT EXISTS BD2 CHARACTER SET = LATIN1;
CREATE DATABASE IF NOT EXISTS BD3 CHARACTER SET = UTF8;

CREATE TABLE BD2.JUEGOS (
	IDJUEGO TINYINT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE CHAR(40) NOT NULL UNIQUE,
    PLATAFORMA SET ('PSP', 'WII', 'PLAYSTATION', 'XBOX', 'NINTENDO DS', 'PC') COMMENT 'Plataformas soportadas por el juego',
	PRECIOVENTA FLOAT(10,2) NULL,
    PRECIOALQUILER FLOAT(10,2),
    STOCKVENTA BIGINT DEFAULT 10 NOT NULL,
    STOCKALQUILER TINYINT ZEROFILL,
    INDEX (PRECIOVENTA)
);

CREATE TABLE BD3.JuegosNuevos LIKE BD2.JUEGOS;
RENAME TABLE BD3.JuegosNuevos TO BD3.NovosXogos;
RENAME TABLE BD3.NovosXogos TO BD2.NovosXogos;
DROP DATABASE IF EXISTS BD3;

CREATE TABLE SOCIOS (
    NUMEROSOCIO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(15) NOT NULL,
    APELLIDOS VARCHAR(35) NOT NULL,
    DNI CHAR(9) UNIQUE COMMENT "EL DNI DEL SOCIO",
    PAIS VARCHAR(20) NULL,
    SEXO ENUM("H", "M"),
    OBSERVACIONES TEXT,
    INDEX (APELLIDOS)
);

CREATE TABLE ALQUILERES (
    IDALQUILER INT AUTO_INCREMENT PRIMARY KEY,
    NUMEROSOCIO MEDIUMINT NOT NULL COMMENT 'REFERENCIA A LA TABLA SOCIOS',
    JUEGO SMALLINT NOT NULL COMMENT 'CÓDIGO DEL JUEGO',
    FECHAALQUILER TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHADEVOLUCION DATETIME,
    FOREIGN KEY (NUMEROSOCIO) REFERENCES SOCIOS(NUMEROSOCIO)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
    ,
    FOREIGN KEY (JUEGO) REFERENCES JUEGOS(IDJUEGO)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
    )
    ENGINE = MyISAM;

CREATE TABLE VENTAS (
    IDVENTA INT PRIMARY KEY AUTO_INCREMENT,
    NUMSOCIO INT NOT NULL COMMENT REFERENCIA A LOS SOCIOS DE LA TABLA SOCIOS,
    JUEGO SMALLINT NOT NULL COMMENT CODIGO DEL JUEGO,
    FECHAVENTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
    PRECIO FLOAT(10,2),
    FOREIGN KEY (NUMSOCIO) REFERENCES SOCIOS(NUMEROSOCIO)
    ON DELETE SET NULL 
    ON UPDATE NO ACTION
    ,
    FOREIGN KEY (JUEGO) REFERENCES JUEGOS(IDJUEGO)
    ON DELETE NO ACTION 
    )
    ENGINE = InnoDB;

SHOW INDEX(SOCIOS) FROM SOCIOS;

DESCRIBE SOCIOS 
SHOW FULL COLUMNS FROM SOCIOS;

SHOW CREATE TABLE SOCIOS;