CREATE DATABASE IF NOT EXISTS BD2 CHARACTER SET = LATIN1;
CREATE DATABASE IF NOT EXISTS BD3 CHARACTER SET = UTF8;

CREATE TABLE BD2.JUEGOS (
	IDJUEGO TINYINT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE CHAR(40) NOT NULL UNIQUE,
    PLATAFORMA SET ('PSP', 'WII', 'PLAYSTATION', 'XBOX', 'NINTENDO DS', 'PC') COMMENT 'Plataformas soportadas por el juego',
	PRECIOVENTA FLOAT(10,2) NULL,
    PRECIOALQUILER FLOAT(10,2),
    STOCKVENTA BIGINT DEFAULT 10 NOT NULL,
    STOCKALQUILER TINYINT ZEROFILL,
    INDEX (PRECIOVENTA)
);

CREATE TABLE BD3.JuegosNuevos LIKE BD2.JUEGOS;
RENAME TABLE BD3.JuegosNuevos TO BD3.NovosXogos;
RENAME TABLE BD3.NovosXogos TO BD2.NovosXogos;
DROP DATABASE IF EXISTS BD3;

CREATE TABLE SOCIOS (
    NUMEROSOCIO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(15) NOT NULL,
    APELLIDOS VARCHAR(35) NOT NULL,
    DNI CHAR(9) UNIQUE COMMENT "EL DNI DEL SOCIO",
    PAIS VARCHAR(20) NULL,
    SEXO ENUM("H", "M"),
    OBSERVACIONES TEXT,
    INDEX (APELLIDOS)
);

CREATE TABLE ALQUILERES (
    IDALQUILER INT AUTO_INCREMENT PRIMARY KEY,
    NUMEROSOCIO MEDIUMINT NOT NULL COMMENT 'REFERENCIA A LA TABLA SOCIOS',
    JUEGO SMALLINT NOT NULL COMMENT 'CÓDIGO DEL JUEGO',
    FECHAALQUILER TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHADEVOLUCION DATETIME,
    FOREIGN KEY (NUMEROSOCIO) REFERENCES SOCIOS(NUMEROSOCIO)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
    ,
    FOREIGN KEY (JUEGO) REFERENCES JUEGOS(IDJUEGO)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
    )
    ENGINE = MyISAM;

CREATE TABLE VENTAS (
    IDVENTA INT PRIMARY KEY AUTO_INCREMENT,
    NUMSOCIO INT NOT NULL COMMENT REFERENCIA A LOS SOCIOS DE LA TABLA SOCIOS,
    JUEGO SMALLINT NOT NULL COMMENT CODIGO DEL JUEGO,
    FECHAVENTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
    PRECIO FLOAT(10,2),
    FOREIGN KEY (NUMSOCIO) REFERENCES SOCIOS(NUMEROSOCIO)
    ON DELETE SET NULL
    ON UPDATE CASCADE
    ,
    FOREIGN KEY (JUEGO) REFERENCES JUEGOS(IDJUEGO)
    ON DELETE NO ACTION 
    )
    ENGINE = InnoDB;

SHOW INDEX(SOCIOS) FROM SOCIOS;

DESCRIBE SOCIOS 
SHOW FULL COLUMNS FROM SOCIOS;

SHOW CREATE TABLE SOCIOS;

-- 20
ALTER TABLE VENTAS ADD NUEVA INT NULL DEFAULT 0 AFTER JUEGO;
-- 21
ALTER TABLE VENTAS ADD (NUEVAS2 INT, NUEVAS3 INT);
-- 22
ALTER TABLE VENTAS CHANGE NUEVAS2 NOVAS2 VARCHAR(255), CHANGE NUEVAS3 NOVAS3 VARCHAR(255);
-- 23
ALTER TABLE VENTAS MODIFY NOVAS2 INT;
-- 24
ALTER TABLE VENTAS DROP NUEVAS3;
-- 25
ALTER TABLE SOCIOS DROP UNIQUE DNI;
-- 26
ALTER TABLE SOCIOS DROP INDEX Apellidos;
-- 27
ALTER TABLE SOCIOS MODIFY NUMEROSOCIOS INT;
-- 28
ALTER TABLE ALQUILERES DROP PRIMARY KEY;
-- 29
ALTER TABLE ALQUILERES ADD PRIMARY KEY (NUMEROSOCIO, JUEGO);
-- 30
ALTER TABLE SOCIOS ADD INDEX DNI;
-- 31
ALTER TABLE INDICESOCIO ADD INDEX (NUMEROSOCIO);
-- 32
ALTER TABLE INDICESOCIO DROP INDEX (NUMEROSOCIO);
-- 33
ALTER TABLE SOCIOS ADD UNIQUE INDEX(NOMBRE, APELLIDOS);
-- 34
ALTER TABLE SOCIOS DROP INDEX (NOMBRE,APELLIDOS);
-- 35
ALTER TABLE VENTAS DROP FOREIGN KEY NUMSOCIO;
ALTER TABLE VENTAS DROP FOREIGN KEY JUEGO;
-- 36
ALTER TABLE VENTAS ADD FOREIGN KEY (NUMEROSOCIO) REFERENCES SOCIOS(NUMEROSOCIO)
    ON DELETE SET NULL
    ON UPDATE CASCADE;

ALTER TABLE VENTAS ADD FOREIGN KEY (JUEGO) REFERENCES JUEGOS(IDJUEGO)
    ON DELETE NO ACTION
-- 37
ALTER TABLE VENTAS MODIFY ENGINE=MyISAM;


/*
27. Modifica el campo numeroSocio en socios y defínelo como entero. ¿Qué
sucede?¿Cómo lo solucionarías?
28. Borra la clave primaria de la tabla alquileres. ¿Qué sucede? ¿Cómo lo
solucionarías?
29. Inserta de nuevo la clave primaria sobre el mismo campo.
30. Inserta un índice sobre el campo DNI de la tabla socios.
31. Crea un índice sobre el nombre de un socio llamado indiceSocio. Comprueba
que el índice tiene el nombre correcto.
32. Borra el índice anterior.
33. Crea un índice único entre el nombre y apellidos de la tabla socios llamado
nombre completo.
34. Borra el índice anterior.
35. Borra las claves foráneas de la tabla ventas.
36. Vuelve a crear las claves foráneas.
37. Cambia el motor de almacenamiento de la tabla ventas a MyISAM
*/
