** CLAUSULAS AVANZADAS DE SELECCION **
    SELECT AVG(PUNTOS) FROM 'JUGADORES' GROUP BY VALORACION; -- AGRUPA DATOS IGUALES EN ESTE CASO DE VALORACION (5, 5, 5) | (7, 7, 7) (*AVG *COUNT *MAX *MIN *SUM)
    SELECT IDDEPART, COUNT(*) FROM 'EMPLEADOS' GROUP BY IDDEPART; -- EL ASTERISCO CUENTA EL TOTAL DE FILAS
    SELECT IDDEPART, COUNT(*) AS 'TOTAL' FROM 'EMPLEADOS' GROUP BY IDDEPART HAVING TOTAL > 3; -- HAVING ES IGUAL AL WHERE PERO PARA GROUP BY
    SELECT OFICIO, COUNT(*) AS 'NUM' FROM 'EMPLEADOS' GROUP BY OFICIO ORDER BY NUM DESC;