SELECT * INTO OUTFILE 'RUTA_ARCHIVO/NOMBRE_ARCHIVO' -- EL ARCHIVO SI NO ESTA CREADO SE CREA AUTOMATICAMENTE
    COLUMNS TERMINATED BY ';'
            ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
FROM 'NOMBRE_TABLA'