**INSERTAR DATOS**

    INSERT INTO NOMBRE_TABLA (DNI, NOMBRE, APELLIDO) VALUES ('99999999X', 'FER', 'LOPEZ', NULL); --(NULL EN CASO DE QUE HAYA UNA CUARTA COLUMNA SIN RELLENAR)--
    INSERT INTO NOMBRE_TABLA (DNI, NOMBRE, APELLIDO) VALUES ('99999999X', 'FER', 'LOPEZ', DEFAULT); --(DEFAULT RELLENA EL CAMPO CON EL DATO ESTANDAR INTRODUCIDO)--
    INSERT INTO NOMBRE_TABLA (DNI, NOMBRE, APELLIDO) VALUES ('99999999X', 'FER', 'LOPEZ', DEFAULT), ('11111111S', 'JAIME', 'DOMINGUEZ', DEFAULT); --AÑADIR MAS COLUMNAS--
    INSERT INTO NOMBRE_TABLA (SET DNI = '99999999X', NOMBRE = 'FER', APELLIDO = 'LOPEZ') --ALTERNATIVA DE INSERCCIÓN--

    INSERT INTO CANTIDAD_VECES (IP, CANTIDAD, FECHA_ULTIMA) VALUES ('192.365.3.80', 1, NOW()) ON DUPLICATE KEY UPDATE CANTIDAD = CANTIDAD + 1, FECHA_ULTIMA = NOW();
    INSERT INTO ALUMNOS2 SELECT * FROM ALUMNOS --COPIAR DATOS DE UNA TABLA A OTRA-- 
    REPLACE INTO ALUMNOS2 SELECT * FROM ALUMNOS --SI NO HAY PRIMARY KEY LO INSERTA, PERO SI HAY UNA PRIMARY KEY YA EN USO LO SUSTITUYE--
    
    --EJERCICIO: TABLA ESCRITORES Y BESTSELLERS CUYAS COLUMNAS SON IDENTICAS DE LAS DOS TABLAS, QUEREMOS INSERTAR EN LA TABLA BESTSELLERS TODOS LOS DATOS DE QUE DISPONEMOS DE LA TABLA ESCRITORES PERO QUE TIENEN UN ID MENOR QUE 5--
    INSERT INTO BESTSELLERS SELECT * FROM ESCRITORES WHERE ID < 5;