LOAD DATA LOCAL INFILE 'C:\USERS\HMONTES\DOCUMENTOS\NUEVASALTAS.TXT' --EN NUESTRO CASO ES SIEMPRE LOCAL + PONER RUTA ABUSOLUTA
LOAD INTO TABLE NOMBRE_TABLA --AÑADIR EN UN TABLA CON DATOS
    REPLACE INTO TABLE EMPLEADOS
    IGNORE INTO TABLE EMPLEADOS
    COLUMNS TERMINATED BY '/t' -- ESTO SI EL TXT TIENE LOS DATOS SEPARADOS POR TABULACIONES 
    COLUMNS TERMINATED BY ',' -- ESTO SI EL TXT TIENE LOS DATOS SEPARADOS POR COMAS 
    ENCLOSED BY '"' -- ESTO SI EL TXT TIENE LOS DATOS CON COMILLAS

    LINES
        STARTING BY "JUG"
        TERMINATED BY "\n"
    IGNORE 1 LINES -- IGNORAR FILAS INICIALES QUE NO SIRVEN DE NADA