** CONSULTAS ANIDADAS **
    * TEST DE COMPARACION EN SUBCONSULTAS * -- Compara una expresión con un único valor
        SELECT NOMBRE, APELLIDO, AULA FROM ALUMNOS WHERE AULA = (
            SELECT AULA FROM ALUMNOS WHERE NOMBRE = 'FRANK'
        );
    
    * TEST DE PERTENENCIA *
        SELECT NOMBRE, APELLIDO FROM ALUMNOS WHERE NOMBRE IN (SELECT NOMBRE FROM ALUMNOS WHERE AULA = 2);
        SELECT NOMBRE, APELLIDO FROM ALUMNOS WHERE NOMBRE NOT IN (SELECT NOMBRE FROM ALUMNOS WHERE AULA = 2);

    * EJERCICIO PRÁCTICA *
    -- SACAR IDDEPART Y NOMBRE DE LOS DEPART QUE NO TENGAN EMPLEADOS
    SELECT IDDEPART, NOMBRE FROM DEPART WHERE IDDEPART NOT IN (
        SELECT IDDEPART FROM EMPLEADOS
    )

    * TEST DE COMPARACION CUANTIFICADA * -- ANY (ALGUNO) Y ALL (TODOS)
    -- SI QUEREMOS OBTENER LOS ALUMNOS CUYA EDAD SEA MAYOR QUE AL MENOS UNO DE LOS ALUMNOS DEL AULA 2
    SELECT * FROM ALUMNOS WHERE EDAD > ANY (
        SELECT EDAD FROM ALUMNOS WHERE AULA = 2
    )

    * TEST DE EXISTENCIA * -- EXISTS OR NOT EXISTS
    -- OBTEN LOS DATOS DE LOS EMPLEADOS QUE NO TENGAN EL MAYOR SALARIO
    SELECT * FROM EMPLEADOS WHERE SALARIO < ANY (
        SELECT SALARIO FROM EMPLEADOS 
    )
