-- BLOQUEOS

    ** BLOQUEO DE LECTURA O COMPARTIDO
        * TU Y EL RESTO DE CONEXIONES SOLO PUEDEN HACER SELECT
        * PUEDE HABER VARIOS BLOQUEOS A LA VEZ
        * READ (TIPO DE BLOQUEO) TODOS PUEDEN LEER TANTO EL QUE LO HIZO COMO LOS OTROS
        * WRITE (TIPO DE BLOQUEO) EL QUE HIZO EL BLOQUEO PUEDE LEER Y ESCRIBIR PERO EL RESTO ESPERA

        * LOCK TABLE nombre_tabla_bloquear TipoDeBloqueo(READ / WRITE); -- BLOQUEAR
        * UNLOCK TABLES; -- DESBLOQUEAR