-- MÁXIMOS DE CONSULTAS POR HORA
    * MAX_QUERIES_PER_HOUR 60

-- MÁXIMOS DE ACTUALIZACIONES POR HORA
    * MAX_UPDATES_PER_HOUR 10
    
-- MÁXIMOS DE CONEXIONES POR HORA
    * MAX_CONNECTIONS_PER_HOUR 100
        
-- MÁXIMOS DE VECES CONECTADO CON EL MISMO USUARIO
    * MAX_USER_CONECTIONS 20

-- CADUCIDAD DE LA CONTRASEÑA
    * CREATE USER hugo@localhost PASSWORD EXPIRE INTERVAL 30 DAY;
    * ALTER USER hugo@localhost PASSWORD EXPIRE INTERVAL 30 DAY;
    * ALTER USER hugo@localhost PASSWORD EXPIRE NEVER; -- NUNCA CADUCA

-- BLOQUEAR CUENTAS DE USUARIO
    * CREATE USER hugo@localhost ACCOUNT LOCK;
    * CREATE USER hugo@localhost ACCOUNT UNLOCK;
    * ALTER USER hugo@localhost ACCOUNT LOCK;
    * ALTER USER hugo@localhost ACCOUNT UNLOCK;