-- TRANSACCIONES (SIRVE PARA VER TODOS LOS CAMBIOS A LA VEZ)
    * START TRANSACTION ... -- INICIAR TRANSACIÓN

    * INSERT (USER HUGO)
    * UPDATE (USER HUGO - HUGO2)
    * INSERT (USER PEPE)

    -- UNA VEZ SE HAGAN TODAS LAS CONSULTAS

    * COMMIT -- APROBAR UN CAMBIO
    * ROLLBACK -- ANULAR UN CAMBIO