-- TRANSACCIONES (SIRVE PARA VER TODOS LOS CAMBIOS A LA VEZ)
-- UNIDAD DE TRABAJO AGRUPA UNA O MAS OPERACIONES QUE DEBEN EJECUTARSE DE FORMA ATÓMICA ES DECIR TODAS DEBEN DE COMPLETARSE CON ÉXITO O NINGUNA DEBE APLICARSE

    * START TRANSACTION -- INICIAR TRANSACIÓN

    * INSERT (USER HUGO)
    * UPDATE (USER HUGO - HUGO2)
    * INSERT (USER PEPE)
    
    -- UNA VEZ SE HAGAN TODAS LAS CONSULTAS

    * COMMIT -- APROBAR UN CAMBIO
    * ROLLBACK -- ANULAR UN CAMBIO
    * SAVEPOINT nombre_punto_recuperación -- GUARDA UN PROGRESO DE LA TRANSACCIÓN
    * RELEASE SAVEPOINT nombre_punto_recuperación -- BORRAR SAVEPOINT

-- EJEMPLO: (BD CUENTAS BANCARIAS)

    * START TRANSACTION

    * UPDATE cuentas SET total = total - 100 WHERE nombre LIKE 'Carlos' OR nombre LIKE 'Diego'; 
    * SAVEPOINT save1
    * UPDATE cuentas SET total = total + 100 WHERE nombre LIKE 'Iago';
    * ROLLBACK TO save1 -- VUELVE HASTA EL SAVEPOINT save1

    * COMMIT